[phases.install]
cmds = [
  'git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"',
  'git config --global --add url."https://github.com/".insteadOf "git@github.com:"',
  'npm install'
]